---
- name: "Add Microsoft apt repo"
  shell:
    cmd: 'wget -q -P /tmp/ https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb && dpkg -i /tmp/packages-microsoft-prod.deb; rm /tmp/packages-microsoft-prod.deb'
  become: true
  become_method: sudo

- name: "Remove docker conflicts"
  shell:
    cmd: 'apt-get purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras; rm -rf /var/lib/docker; rm -rf /var/lib/containerd'
  become: true
  become_method: sudo

- name: "Add docker key"
  shell:
    cmd: 'mkdir -p /etc/apt/keyrings; curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg; chmod a+r /etc/apt/keyrings/docker.gpg'
  become: true
  become_method: sudo

- name: "Add Docker apt repo"
  shell:
    cmd: 'echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'
  become: true
  become_method: sudo

- name: "Update system"
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  become: true
  become_method: sudo


- name: "Installing Packages"
  package:
    name:
      - python3-full
      - pipx
      - jq
      - ntpdate
      - flameshot
      - exiftool
      - golang
      - kitty
      - i3
      - dmenu
      - zsh
      - openvpn
      - ftp
      - awscli
      - seclists
      - chrony
      - rsyslog
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
  become: true
  become_method: sudo
