- name: Create a directory for SysinternalsSuite
  file:
    path: '{{ ansible_env.HOME }}/ToolRepositories/SysinternalsSuite'
    state: directory

- name: Downloading SysinternalsSuite.zip
  unarchive:
    src: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: '{{ ansible_env.HOME }}/ToolRepositories/SysinternalsSuite'
    remote_src: yes
