- name: Upgrade system
  shell:
    cmd: 'parrot-upgrade'
  become: true

- name: cleanup apt sources
  shell:
    cmd: 'rm /etc/apt/sources.list'
  ignore_errors: yes
  become: true

- name: Install apt packages
  package:
    name:
      - python3-full
      - pipx
      - jq
      - kitty
      - i3
      - i3status
      - dmenu
      - zsh
      - openvpn
      - seclists
      - chrony
      - rsyslog
      - tmux
      - vim
      - golang
      - openjdk-11-jdk
      - bloodhound
      - ntpdate
      - exiftool
      - golang
      - ftp
      - nfs-common
      - freerdp3-x11
      - freerdp2-x11
      - krb5-user
      - ncat
    state: latest
    autoremove: true
    autoclean: true
    update_cache: yes
  ignore_errors: yes
  become: true

- name: Install GEF
  shell:
    cmd: 'bash -c "$(curl -fsSL https://gef.blah.cat/sh)"'

- name: Install UV
  shell:
    cmd: 'curl -LsSf https://astral.sh/uv/install.sh | sh'

- name: Ensure the ToolRepositories directory exists
  file:
    path: '{{ ansible_env.HOME }}/ToolRepositories'
    state: directory

- import_tasks: setup-burpsuite.yml
- import_tasks: install-sysinternals.yml
- import_tasks: install-kerbrute.yml
- import_tasks: install-ligolong.yml
- import_tasks: install-sliver.yml
- import_tasks: install-dockerce.yml
- import_tasks: install-obsidian.yml
- import_tasks: install-powershell.yml
- import_tasks: install-chisel.yml
- import_tasks: install-aquatone.yml

- name: Install feroxbuster
  shell:
    cmd: 'bash -c "curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | bash -s $HOME/.local/bin"'

- name: Downlaod useful github repositories
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.location }}'
  loop:
    - repo: 'https://github.com/Flangvik/SharpCollection'
      location: '{{ ansible_env.HOME }}/ToolRepositories/SharpCollection'
    - repo: 'https://github.com/lgandx/Responder'
      location: '{{ ansible_env.HOME }}/ToolRepositories/Responder'
    - repo: 'https://github.com/urbanadventurer/username-anarchy'
      location: '{{ ansible_env.HOME }}/ToolRepositories/username-anarchy'
    - repo: 'https://github.com/dirkjanm/BloodHound.py'
      location: '{{ ansible_env.HOME }}/ToolRepositories/BloodHound-python'
    - repo: 'https://github.com/peass-ng/PEASS-ng'
      location: '{{ ansible_env.HOME }}/ToolRepositories/PEASS-ng'
    - repo: 'https://github.com/AlessandroZ/LaZagne'
      location: '{{ ansible_env.HOME }}/ToolRepositories/LaZagne'
    - repo: 'https://github.com/RedSiege/EyeWitness'
      location: '{{ ansible_env.HOME }}/ToolRepositories/EyeWitness'
    - repo: 'https://github.com/Kevin-Robertson/Inveigh'
      location: '{{ ansible_env.HOME }}/ToolRepositories/Inveigh'
      
- name: Downloading dump_emails_imap.py
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.location }}'
  loop:
    - url: 'https://gist.githubusercontent.com/s3rgeym/b7c6cec188430b6b57dec71a5240c277/raw/fa72dc7a0310a1b09d02e76be0ad417e5789800e/dump_emails.py'
      location: '{{ ansible_env.HOME }}/ToolRepositories/dump_emails_imap.py'

- name: Install python tools with uv
  shell:
    cmd: 'uv tool install {{ item }} --upgrade --force'
  with_list:
    - 'git+https://github.com/fortra/impacket.git'
    - 'git+https://github.com/ly4k/Certipy.git'
    - 'git+https://github.com/Pennyw0rth/NetExec'
    - 'git+https://github.com/skelsec/pypykatz'
    - 'git+https://github.com/cddmp/enum4linux-ng'
    - 'git+https://github.com/CravateRouge/bloodyAD'
    - 'git+https://github.com/arthaud/git-dumper'
    - 'git+https://github.com/Paliak/PKINITtools'
      
- name: Installing tools from Gems
  gem:
    name: '{{ item }}'
    state: latest
    user_install: false
  loop:
    - logger
    - stringio
    - winrm
    - builder
    - erubi
    - gssapi
    - gyoku
    - httpclient
    - logging
    - little-plugger
    - nori
    - rubyntlm
    - winrm-fs
    - evil-winrm
  become: true
