- name: Check if BurpSuiteCA.der exists
  stat:
    path: '{{ burpsuite_cert_path }}'
  register: burp_cert
  
- name: Install certificate
  block:
    - name: Start Burpsuite
      expect:
        command: '{{ burpsuite_start_command }}'
        responses:
          Do you accept the terms and conditions: 'y'
      async: '{{ burpsuite_timeout }}'
      poll: 0
    - name: Wait for BurpSuite to load.
      ansible.builtin.wait_for:
        timeout: '{{ burpsuite_timeout }}'
        port: 8080
    - name: Move certificate
      ansible.builtin.get_url:
        url: 'http://127.0.0.1:8080/cert'
        dest: '{{ burpsuite_cert_path }}'
        owner: root
        group: root
        mode: 420
      register: cert_moved
      become: true
  when: burp_cert.stat.exists == False
  
- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: '{{ burpsuite_extras_dir }}'
    state: directory
    mode: '0755'
  become: true
  
- name: Download burpuite jar files
  get_url:
    url: '{{ item.value.url }}'
    dest: '{{ burpsuite_extras_dir }}/{{ item.value.jar }}'
    checksum: '{{ item.value.checksum }}'
    mode: '0644'
  become: true
  loop: '{{ lookup(''dict'', burpsuite_extras_jars) }}'