---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
              - zsh-autosuggestions
              - zsh-syntax-highlighting
    - role: "roles/customize-terminal"
