---
- name: "Disable ssh"
  service:
    name: ssh
    enabled: false
    state: stopped
  become: yes
  become_method: sudo

- name: "Install pam logging script"
  copy:
    src: "{{ role_path }}/files/pamLogger.sh"
    dest: "/opt/pamLogger.sh"
  become: yes
  become_method: sudo

- name: "Log ssh login attemps"
  lineinfile:
    path: /etc/pam.d/common-auth
    line: "#auth optional pam_exec.so quiet expose_authtok /opt/pamLogger.sh"
    insertbefore: "# here are the per-package modules (the "Primary" block)"
  become: yes
  become_method: sudo
