- name: Extract CascadiaCode.tar.xz
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.tar.xz
    dest: /usr/share/fonts
    remote_src: yes
  become: true

- name: Extract CascadiaMono.tar.xz
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.tar.xz
    dest: /usr/share/fonts
    remote_src: yes
  become: true
  
- name: Refresh font cache
  shell:
    cmd: fc-cache -f -v
  become: true