---
- name: "Configuring eth"
  community.general.nmcli:
    conn_name: 'System "Wired connection 1"'
    ifname: "Wired connection 1"
    type: ethernet
    state: present
    autoconnect: yes
    ip4: 10.0.2.15
    gw4: 10.0.2.2
    dns4:
      - 1.1.1.1