---
- name: "Configuring eth"
  nmcli:
    conn_name: "System {{ ansible_default_ipv4.interface }}"
    ifname: {{ ansible_default_ipv4.interface }}
    type: ethernet
    state: present
    autoconnect: yes
    ip4: 10.0.2.15
    gw4: 10.0.2.2
    dns4:
      - 1.1.1.3