---
- name: "Configuring eth"
  community.general.nmcli:
    conn_name: 'System "Wired connection 1"'
    ifname: "Wired connection 1"
    type: ethernet
    state: present
    autoconnect: yes
    ip4: 10.0.2.15
    gw4: 10.0.2.2
    dns4:
      - 1.1.1.1

- name: "Remove unnecessary autostart entries"
  shell:
    cmd: 'rm -rf /etc/xdg/autostart/*'
  become: true
  become_method: sudo

- name: Disable unnecessary services
  service:
    name:    '{{ item }}'
    enabled: no
    state:   stopped
  with_items:
    - ModemManager.service
    - opensnitch.service
    - upower.service
    - wpa_supplicant.service
  register: service_disable_result
  failed_when: "Could not find the requested service"
  become: true
  become_method: sudo
