- name: Configuring eth
  community.general.nmcli:
    conn_name: '{{ connection_name }}'
    type: ethernet
    state: present
    autoconnect: 'yes'
    ip4: '{{ ipv4 }}'
    gw4: '{{ gateway }}'
    dns4:
      - '{{ dns }}'
     
- name: Remove unnecessary autostart entries
  shell:
    cmd: rm -rf /etc/xdg/autostart/*
  become: true
     
- name: Disable unnecessary services
  service:
    name: '{{ item }}'
    enabled: 'no'
    state: stopped
  with_items:
    - ModemManager.service
    - opensnitch.service
    - upower.service
    - wpa_supplicant.service
  ignore_errors: yes
  become: true

- name: Updating Firefox Policies
  template:
    src: templates/policies.json.j2
    dest: /usr/share/firefox-esr/distribution/policies.json
  become: true
  
- import_tasks: install-fonts.yml
- import_tasks: setup-logging.yml
- import_tasks: install-dotfiles.yml