- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
  become: true

- name: Check if Samba UFW profile exists
  stat:
    path: /etc/ufw/applications.d/samba
  register: samba_profile

- name: Create Samba UFW profile
  copy:
    dest: /etc/ufw/applications.d/samba
    content: |
      [Samba]
      title=LanManager-like file and printer server for Unix
      description=The Samba software suite is a collection of programs that implements the SMB/CIFS protocol in Unix systems
      ports=137,138/udp|139,445/tcp
    mode: '0644'
    owner: root
    group: root
  when: not samba_profile.stat.exists

- name: Allow Samba
  ufw:
    rule: allow
    app: Samba
  become: true

- name: Allow Custom Ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 8000
    - 8080
    - 9001
    - 9002
    - 9003
  become: true

- name: Log SYN packets in INPUT Chain
  lineinfile:
    path: /etc/ufw/after.rules
    line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
    insertbefore: '# don''t delete the ''COMMIT'' line or these rules won''t be processed'
  become: true
  
- name: Restart ufw
  service:
    name: ufw
    state: restarted
  become: true
  