- name: Enable rsyslog service
  service:
    name: rsyslog
    enabled: 'yes'
    state: started
  become: true
  
- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
  become: true
  
- name: Log SYN packets in INPUT Chain
  lineinfile:
    path: /etc/ufw/after.rules
    line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
    insertbefore: '# don''t delete the ''COMMIT'' line or these rules won''t be processed'
  become: true
  
- name: Restart ufw
  service:
    name: ufw
    state: restarted
  become: true
  
- name: Disable ssh
  service:
    name: ssh
    enabled: false
    state: stopped
  become: true
  
- name: Install pam logging script
  copy:
    src: '{{ role_path }}/files/pamLogger.sh'
    dest: /opt/pamLogger.sh
  become: true
  
- name: Log ssh login attemps
  lineinfile:
    path: /etc/pam.d/common-auth
    line: '#auth optional pam_exec.so quiet expose_authtok /opt/pamLogger.sh'
    insertbefore: '# here are the per-package modules (the "Primary" block)'
  become: true
  
- name: Install auditd
  package:
    name: auditd
    state: present
  become: true
  
- name: Configure Audit Rules
  copy:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: 416
  become: true
  
- name: Create _laurel user
  user:
    name: _laurel
    state: present
    shell: /bin/false
    create_home: 'no'
    home: /var/log/laurel
  become: true
  
- name: Create directories for _laurel /var/log/laurel
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner | default(''root'') }}'
    group: '{{ item.group | default(''root'') }}'
    mode: '{{ item.mode | default(''0750'') }}'
  loop:
    - path: /var/log/laurel
      owner: _laurel
      group: _laurel
    - path: /tmp/laurel
      owner: _laurel
      group: _laurel
    - path: /etc/laurel
  become: true
  async: 15
  poll: 0
  
- name: Copy laurel/config.toml to /etc/laurel/config.toml
  copy:
    src: laurel/config.toml
    dest: /etc/laurel/config.toml
    owner: _laurel
    group: _laurel
    mode: 416
  become: true
  
- name: Copy laurel/laurel.conf to /etc/audit/plugins.d
  copy:
    src: laurel/laurel.conf
    dest: /etc/audit/plugins.d/laurel.conf
    owner: root
    group: root
    mode: 416
  become: true
  
- name: Downloading https://github.com/threathunters-io/laurel/releases/download/v0.5.2/laurel-v0.5.2-x86_64-glibc.tar.gz
  get_url:
    url: https://github.com/threathunters-io/laurel/releases/download/v0.5.2/laurel-v0.5.2-x86_64-glibc.tar.gz
    dest: /tmp/laurel-v0.5.2-x86_64-glibc.tar.gz
    mode: 416
    
- name: Extract /tmp/laurel-v0.5.2-x86_64-glibc.tar.gz
  unarchive:
    src: /tmp/laurel-v0.5.2-x86_64-glibc.tar.gz
    dest: /tmp/laurel/
    owner: root
    group: root
    mode: 493
  become: true
  
- name: Running install -m755 laurel /usr/local/sbin/laurel
  command: install -m755 laurel /usr/local/sbin/laurel
  args:
    chdir: /tmp/laurel/
  become: true
  
- name: Restart auditd
  service:
    name: auditd
    state: restarted
  become: true
