- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert
  
- name: "Install certificate"
  block:
    - name: "Start Burpsuite"
      command: "java -Djava.awt.headless=true -jar /usr/share/burpsuite/burpsuite.jar < <(echo y)"
      async: 300
      poll: 0

    - name: "Wait for BurpSuite to load."
      ansible.builtin.wait_for:
        port: 8080

    - name: "Move certificate"
      ansible.builtin.get_url:
          url: http://127.0.0.1:8080/cert
          dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
          owner: root
          group: root
          mode: 0644
      register: cert_moved
      become: true
      become_method: sudo
  when: burp_cert.stat.exists == False

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    mode: '0644'
  become: true
  become_method: sudo
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"
  
- name: Copy BurpSuite Community Config
  template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigCommunity.json"

